/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.net.UnknownHostException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.table.DefaultTableModel;

import controllers.PessoaFisicaCollection;
import model.PessoaFisica;

/**
 *
 * @author eduardocorreadesa
 */
public class EditarPessoaFisica extends javax.swing.JFrame {
	String cpf = null;
	/**
	 * Creates new form EditarPessoaFisica
	 */
	public EditarPessoaFisica() {
		initComponents();
		this.setLocationRelativeTo(null);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		tabelaPessoaFisica = new javax.swing.JTable();
		jLabel2 = new javax.swing.JLabel();
		inputNome = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		inputDataNascimento = new javax.swing.JTextField();
		inputEstadoCivil = new javax.swing.JTextField();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		inputAgencia = new javax.swing.JTextField();
		inputConta = new javax.swing.JTextField();
		jLabel8 = new javax.swing.JLabel();
		inputLimite = new javax.swing.JTextField();
		jLabel9 = new javax.swing.JLabel();
		inputSexo = new javax.swing.JTextField();
		btnSalvar = new javax.swing.JButton();
		btnVoltarCancelar = new javax.swing.JButton();
		btnPesquisar = new javax.swing.JButton();
		btnExluir = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setText("Editar Pessoa Fisica");

		tabelaPessoaFisica.setModel(new javax.swing.table.DefaultTableModel(
				new Object [][] {
					{null, null, null, null, null, null, null, null},
					{null, null, null, null, null, null, null, null},
					{null, null, null, null, null, null, null, null},
					{null, null, null, null, null, null, null, null}
				},
				new String [] {
						"Nome", "CPF", "Data Nascimento", "Sexo", "Estado Civil", "Agencia", "Conta", "Limite R$"
				}
				));
		tabelaPessoaFisica.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				tabelaPessoaFisicaMouseClicked(evt);
			}
		});
		jScrollPane1.setViewportView(tabelaPessoaFisica);

		jLabel2.setText("Nome:");

		jLabel4.setText("Data Nascimento:");

		jLabel5.setText("Estado Civil:");

		jLabel6.setText("Agencia:");

		jLabel7.setText("Conta:");

		inputConta.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				inputContaActionPerformed(evt);
			}
		});

		jLabel8.setText("Limite R$:");

		inputLimite.setToolTipText("");

		jLabel9.setText("Sexo:");

		inputSexo.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				inputSexoActionPerformed(evt);
			}
		});

		btnSalvar.setText("Salvar");
		btnSalvar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnSalvarActionPerformed(evt);
			}
		});

		btnVoltarCancelar.setText("Voltar/ Cancelar");
		btnVoltarCancelar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnVoltarCancelarActionPerformed(evt);
			}
		});

		btnPesquisar.setText("Pesquisar");
		btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnPesquisarActionPerformed(evt);
			}
		});

		btnExluir.setText("Excluir");
		btnExluir.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnExluirActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jLabel1)
						.addGap(223, 223, 223))
				.addGroup(layout.createSequentialGroup()
						.addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup()
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
												.addGroup(layout.createSequentialGroup()
														.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
																.addComponent(jLabel2)
																.addComponent(jLabel9))
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
																.addComponent(inputNome)
																.addComponent(inputSexo, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
														.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
																.addComponent(jLabel4)
																.addComponent(jLabel5))
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
																.addComponent(inputDataNascimento)
																.addComponent(inputEstadoCivil, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
																.addComponent(jLabel6)
																.addComponent(jLabel7)
																.addComponent(jLabel8))
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(inputAgencia)
																.addComponent(inputConta)
																.addComponent(inputLimite))))
										.addContainerGap())
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
										.addComponent(btnExluir)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(btnPesquisar)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(btnVoltarCancelar)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(btnSalvar))))
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(jLabel1)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel2)
								.addComponent(inputNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel4)
								.addComponent(inputDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel6)
								.addComponent(inputAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup()
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel5)
												.addComponent(inputEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel7)
												.addComponent(inputConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel8)
												.addComponent(inputLimite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jLabel9)
										.addComponent(inputSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(btnSalvar)
								.addComponent(btnVoltarCancelar)
								.addComponent(btnPesquisar)))
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(btnExluir)
						.addContainerGap())
				);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void btnVoltarCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarCancelarActionPerformed
		this.dispose();

	}//GEN-LAST:event_btnVoltarCancelarActionPerformed

	private void inputSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputSexoActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_inputSexoActionPerformed

	private void inputContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputContaActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_inputContaActionPerformed

	private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed

		inputNome.setText("");
		inputSexo.setText("");
		inputDataNascimento.setText("");
		inputEstadoCivil.setText("");
		inputAgencia.setText("");
		inputConta.setText("");
		inputLimite.setText("");
		try {

			DefaultTableModel model = (DefaultTableModel) tabelaPessoaFisica.getModel();
			model.setNumRows(0); 


			PessoaFisicaCollection  listPessoa = new PessoaFisicaCollection();


			ArrayList<PessoaFisica> cnts = listPessoa.getPessoaFisica();


			for (PessoaFisica c : cnts) {              
				//aqui vc colaca os valores que vc quer capturar da lista de contatos
				model.addRow(new Object[]{c.getNome(), c.getCpf(), c.getDataNascimento(), c.getSexo(), c.getEstadoCivil(), c.getAgencia(), c.getConta(), c.getLimite()});           
			}       


		} catch (Exception ex) {
			Logger.getLogger(ListarPessoaFisica.class.getName()).log(Level.SEVERE, null, ex);
		}
	}//GEN-LAST:event_btnPesquisarActionPerformed

	private void tabelaPessoaFisicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaPessoaFisicaMouseClicked

		int row = tabelaPessoaFisica.getSelectedRow();
		cpf  = tabelaPessoaFisica.getValueAt(row, 1).toString();
		PessoaFisica pessoa = null;
		try {
			pessoa = PessoaFisicaCollection.getPessoaFisicaPorCPF(cpf);
		} catch (UnknownHostException ex) {
			Logger.getLogger(EditarPessoaFisica.class.getName()).log(Level.SEVERE, null, ex);
		}

		inputNome.setText(pessoa.getNome());
		inputSexo.setText(pessoa.getSexo());
		inputDataNascimento.setText(pessoa.getDataNascimento());
		inputEstadoCivil.setText(pessoa.getEstadoCivil());
		inputAgencia.setText(pessoa.getAgencia());
		inputConta.setText(pessoa.getConta());
		inputLimite.setText(pessoa.getLimite());

	}//GEN-LAST:event_tabelaPessoaFisicaMouseClicked

	private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed


		try {
			model.PessoaFisica pessoa = new PessoaFisica();

			pessoa.setNome(inputNome.getText());

			pessoa.setDataNascimento(inputDataNascimento.getText());
			pessoa.setAgencia(inputAgencia.getText());
			pessoa.setConta(inputConta.getText());
			pessoa.setSexo(inputSexo.getText());
			pessoa.setEstadoCivil(inputEstadoCivil.getText());
			pessoa.setLimite(inputLimite.getText());


			controllers.PessoaFisicaCollection pessoaFisica = new controllers.PessoaFisicaCollection();
			inputNome.setText("");
			inputDataNascimento.setText("");
			inputAgencia.setText("");
			inputConta.setText("");
			inputSexo.setText("");
			inputEstadoCivil.setText("");
			inputLimite.setText("");


			pessoaFisica.updatePessoaFisicaPorCPF(cpf, pessoa);

		} catch (UnknownHostException ex) {
			Logger.getLogger(CadastrarPessoaFisica.class.getName()).log(Level.SEVERE, null, ex);
		}

		btnPesquisarActionPerformed(evt);

	}//GEN-LAST:event_btnSalvarActionPerformed

	private void btnExluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExluirActionPerformed


		try {
			model.PessoaFisica pessoa = new PessoaFisica();

			pessoa.setNome(inputNome.getText());

			pessoa.setDataNascimento(inputDataNascimento.getText());
			pessoa.setAgencia(inputAgencia.getText());
			pessoa.setConta(inputConta.getText());
			pessoa.setSexo(inputSexo.getText());
			pessoa.setEstadoCivil(inputEstadoCivil.getText());
			pessoa.setLimite(inputLimite.getText());


			controllers.PessoaFisicaCollection pessoaFisica = new controllers.PessoaFisicaCollection();
			inputNome.setText("");
			inputDataNascimento.setText("");
			inputAgencia.setText("");
			inputConta.setText("");
			inputSexo.setText("");
			inputEstadoCivil.setText("");
			inputLimite.setText("");


			pessoaFisica.removePessoaFisicaPorCPF(cpf, pessoa);

		} catch (UnknownHostException ex) {
			Logger.getLogger(CadastrarPessoaFisica.class.getName()).log(Level.SEVERE, null, ex);
		}

		btnPesquisarActionPerformed(evt);
	}//GEN-LAST:event_btnExluirActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(EditarPessoaFisica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(EditarPessoaFisica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(EditarPessoaFisica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(EditarPessoaFisica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new EditarPessoaFisica().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnExluir;
	private javax.swing.JButton btnPesquisar;
	private javax.swing.JButton btnSalvar;
	private javax.swing.JButton btnVoltarCancelar;
	private javax.swing.JTextField inputAgencia;
	private javax.swing.JTextField inputConta;
	private javax.swing.JTextField inputDataNascimento;
	private javax.swing.JTextField inputEstadoCivil;
	private javax.swing.JTextField inputLimite;
	private javax.swing.JTextField inputNome;
	private javax.swing.JTextField inputSexo;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable tabelaPessoaFisica;
	// End of variables declaration//GEN-END:variables
}
