/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.OperacaoFinanceira;
import java.net.UnknownHostException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import model.PessoaFisica;

import model.Util;


/**
 *
 * @author eduardocorreadesa
 */
public class Sacar extends javax.swing.JFrame {

	/**
	 * Creates new form Sacar
	 */
	public Sacar() {
		initComponents();
		this.setLocationRelativeTo(null);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		btnPesquisarCorrentista = new javax.swing.JButton();
		jLabel3 = new javax.swing.JLabel();
		inputSaldo = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		inputSacar = new javax.swing.JTextField();
		btnSacar = new javax.swing.JButton();
		btnVoltar = new javax.swing.JButton();
		jLabel5 = new javax.swing.JLabel();
		inputNome = new javax.swing.JTextField();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setText("Operação Sacar");

		btnPesquisarCorrentista.setText("Pesquisar");
		btnPesquisarCorrentista.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnPesquisarCorrentistaActionPerformed(evt);
			}
		});

		jLabel3.setText("Saldo R$:");

		jLabel4.setText("Sacar: R$:");

		btnSacar.setText("Sacar");
		btnSacar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnSacarActionPerformed(evt);
			}
		});

		btnVoltar.setText("Voltar");
		btnVoltar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnVoltarActionPerformed(evt);
			}
		});

		jLabel5.setText("Nome:");

		inputNome.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusGained(java.awt.event.FocusEvent evt) {
				inputNomeFocusGained(evt);
			}
		});
		inputNome.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				inputNomeActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(btnVoltar)
						.addContainerGap())
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addGroup(layout.createSequentialGroup()
										.addContainerGap(135, Short.MAX_VALUE)
										.addComponent(jLabel1))
								.addGroup(layout.createSequentialGroup()
										.addGap(19, 19, 19)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(jLabel4)
												.addComponent(jLabel3)
												.addComponent(jLabel5))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(inputSaldo)
												.addComponent(inputSacar)
												.addComponent(inputNome))))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(btnPesquisarCorrentista)
								.addComponent(btnSacar))
						.addGap(59, 59, 59))
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(jLabel1)
						.addGap(18, 18, 18)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(btnPesquisarCorrentista)
								.addComponent(jLabel5)
								.addComponent(inputNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(90, 90, 90)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel4)
								.addComponent(inputSacar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(btnSacar))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel3)
								.addComponent(inputSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
						.addComponent(btnVoltar)
						.addContainerGap())
				);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void btnPesquisarCorrentistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarCorrentistaActionPerformed
		JFrame janela = new ListarPessoaFisicaPessoaJuridica();
		janela.setVisible(true);
		this.dispose();



	}//GEN-LAST:event_btnPesquisarCorrentistaActionPerformed

	private void btnSacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacarActionPerformed

		OperacaoFinanceira.debitarSaldo(Util.CPFCNPJ, inputSacar.getText().toString());
		inputSacar.setText("");
		try {
			inputSaldo.setText(OperacaoFinanceira.getSaldoPessoaJuridicaPessoaFisica(Util.CPFCNPJ).toString());
		} catch (UnknownHostException ex) {
			Logger.getLogger(Sacar.class.getName()).log(Level.SEVERE, null, ex);
		}

	}//GEN-LAST:event_btnSacarActionPerformed

	private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
		Util.CPFCNPJ = null;
		Util.NOME = null;
		this.dispose();
	}//GEN-LAST:event_btnVoltarActionPerformed

	private void inputNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputNomeFocusGained
		inputNome.setText(Util.NOME);
		String saldo = null;
		try {            
			saldo = OperacaoFinanceira.getSaldoPessoaJuridicaPessoaFisica(Util.CPFCNPJ);
		} catch (UnknownHostException ex) {
			Logger.getLogger(Sacar.class.getName()).log(Level.SEVERE, null, ex);
		}
		inputSaldo.setText(saldo);

	}//GEN-LAST:event_inputNomeFocusGained

	private void inputNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNomeActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_inputNomeActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Sacar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Sacar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Sacar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Sacar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Sacar().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnPesquisarCorrentista;
	private javax.swing.JButton btnSacar;
	private javax.swing.JButton btnVoltar;
	private javax.swing.JTextField inputNome;
	private javax.swing.JTextField inputSacar;
	private javax.swing.JTextField inputSaldo;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	// End of variables declaration//GEN-END:variables
}
