/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.PessoaFisicaCollection;
import controllers.PessoaJuridicaCollection;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import model.PessoaFisica;
import model.PessoaJuridica;

/**
 *
 * @author eduardocorreadesa
 */
public class ListarAgenciaConta extends javax.swing.JFrame {

	/**
	 * Creates new form ListarAgenciaConta
	 */
	public ListarAgenciaConta() {
		initComponents();
		this.setLocationRelativeTo(null);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		tabelaAgenciaConta = new javax.swing.JTable();
		btnVoltar = new javax.swing.JButton();
		btnAtualizar = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setText("Agencia e Conta por Correntista");

		tabelaAgenciaConta.setModel(new javax.swing.table.DefaultTableModel(
				new Object [][] {
					{null, null, null},
					{null, null, null},
					{null, null, null},
					{null, null, null}
				},
				new String [] {
						"Agencia", "Conta", "Correntista"
				}
				));
		jScrollPane1.setViewportView(tabelaAgenciaConta);

		btnVoltar.setText("Voltar");
		btnVoltar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnVoltarActionPerformed(evt);
			}
		});

		btnAtualizar.setText("Listar");
		btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnAtualizarActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addGap(95, 95, 95)
						.addComponent(jLabel1)
						.addContainerGap(104, Short.MAX_VALUE))
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
						.addContainerGap())
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
						.addGap(0, 0, Short.MAX_VALUE)
						.addComponent(btnAtualizar)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(btnVoltar))
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(jLabel1)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(btnVoltar)
								.addComponent(btnAtualizar))
						.addContainerGap())
				);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
		try {
			DefaultTableModel model = (DefaultTableModel) tabelaAgenciaConta.getModel();
			model.setNumRows(0); 


			PessoaFisicaCollection  listPessoa = new PessoaFisicaCollection();


			ArrayList<PessoaFisica> cnts = listPessoa.getPessoaFisica();


			for (PessoaFisica c : cnts) {              
				//aqui vc colaca os valores que vc quer capturar da lista de contatos
				model.addRow(new Object[]{c.getAgencia(), c.getConta(), c.getNome()});           
			} 

			PessoaJuridicaCollection  listPessoaJuridica = new PessoaJuridicaCollection();
			ArrayList<PessoaJuridica> juridica = listPessoaJuridica.getPessoaJuridica();

			for (PessoaJuridica c : juridica) {              
				model.addRow(new Object[]{c.getAgencia(), c.getConta(), c.getNomeFantasia()});           
			}




		} catch (Exception ex) {
			Logger.getLogger(ListarPessoaFisica.class.getName()).log(Level.SEVERE, null, ex);
		}
	}//GEN-LAST:event_btnAtualizarActionPerformed

	private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
		this.dispose();
	}//GEN-LAST:event_btnVoltarActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(ListarAgenciaConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(ListarAgenciaConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(ListarAgenciaConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(ListarAgenciaConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ListarAgenciaConta().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnAtualizar;
	private javax.swing.JButton btnVoltar;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable tabelaAgenciaConta;
	// End of variables declaration//GEN-END:variables
}
